[[install]]
== Installation

{eh} binaries can be obtained either by downloading them from the http://elastic.co[elastic.co] site as a ZIP (containing project jars, sources and documentation) or by using any http://maven.apache.org/[Maven]-compatible tool with the following dependency:

["source","xml",subs="attributes"]
----
<dependency>
  <groupId>org.elasticsearch</groupId>
  <artifactId>elasticsearch-hadoop</artifactId>
  <version>{ver}</version>
</dependency>
----

The jar above contains all the features of {eh} and does not require any other dependencies at runtime; in other words it can be used as is.

[[yarn]]
{eh} binary is suitable for both Hadoop 1.x and Hadoop 2.x (also known as YARN) environments without any changes.

=== Minimalistic binaries

In addition to the 'uber' jar, {eh} provides minimalistic jars for each integration, tailored for those who use just _one_ module (in all other situations the `uber` jar is recommended); the jars are smaller in size and use a dedicated pom, covering only the needed dependencies.
These are available under the same `groupId`, using an `artifactId` with the pattern `elasticsearch-hadoop-{integration}`:

.Map/Reduce
["source","xml",subs="attributes"]
----
<dependency>
  <groupId>org.elasticsearch</groupId>
  <artifactId>elasticsearch-hadoop-mr<1></artifactId>
  <version>{ver}</version>
</dependency>
----

<1> 'mr' artifact

.Apache Hive
["source","xml",subs="attributes"]
----
<dependency>
  <groupId>org.elasticsearch</groupId>
  <artifactId>elasticsearch-hadoop-hive<1></artifactId>
  <version>{ver}</version>
</dependency>
----

<1> 'hive' artifact

.Apache Pig
["source","xml",subs="attributes"]
----
<dependency>
  <groupId>org.elasticsearch</groupId>
  <artifactId>elasticsearch-hadoop-pig<1></artifactId>
  <version>{ver}</version>
</dependency>
----

<1> 'pig' artifact

.Apache Spark
["source","xml",subs="attributes"]
----
<dependency>
  <groupId>org.elasticsearch</groupId>
  <artifactId>elasticsearch-spark_2.10<1></artifactId>
  <version>{ver}</version>
</dependency>
----

<1> 'spark' artifact. Notice the `_2.10` suffix which indicates the Scala version compatible with the artifact. Currently it is the same as the version used by Spark itself.

.Cascading
["source","xml",subs="attributes"]
----
<dependency>
  <groupId>org.elasticsearch</groupId>
  <artifactId>elasticsearch-hadoop-cascading<1></artifactId>
  <version>{ver}</version>
</dependency>
----

<1> 'cascading' artifact

Note that Cascading itself is not available in Maven central but rather in its own repo http://conjars.org/[conjars.org]. Make sure to add this repository to your build configuration
in order for the Cascading dependencies to be properly resolved:

[source,xml]
----
<repositories>
  <repository>
    <id>conjars.org</id>
    <url>http://conjars.org/repo</url>
  </repository>
</repositories>
----

.Storm
["source","xml",subs="attributes"]
----
<dependency>
  <groupId>org.elasticsearch</groupId>
  <artifactId>elasticsearch-storm<1></artifactId>
  <version>{ver}</version>
</dependency>
----

<1> 'storm' artifact

Releases are available in the central Maven http://repo1.maven.org/maven[repository].

[[download-dev]]
=== Development Builds

Development (or nightly or snapshots) builds are published daily at 'sonatype-oss' repository (see below). Make sure to use snapshot versioning:

["source","xml",subs="attributes"]
----
<dependency>
  <groupId>org.elasticsearch</groupId>
  <artifactId>elasticsearch-hadoop</artifactId>
  <version>{ver-d}</version> <1>
</dependency>
----

<1> notice the 'BUILD-SNAPSHOT' suffix indicating a development build

but also enable the dedicated snapshots repository :

[source,xml]
----
<repositories>
  <repository>
    <id>sonatype-oss</id>
    <url>http://oss.sonatype.org/content/repositories/snapshots</url> <1>
    <snapshots><enabled>true</enabled></snapshots> <2>
  </repository>
</repositories>
----

<1> add snapshot repository
<2> enable 'snapshots' capability on the repository otherwise these will not be found by Maven