[[install]]
== Installation

{eh} binaries can be obtained either by downloading them from the http://elastic.co[elastic.co] site as a ZIP (containing project jars, sources and documentation) or by using any http://maven.apache.org/[Maven]-compatible tool with the following dependency:

["source","xml",subs="attributes"]
----
<dependency>
  <groupId>org.elasticsearch</groupId>
  <artifactId>elasticsearch-hadoop</artifactId>
  <version>{ver}</version>
</dependency>
----

The jar above contains all the features of {eh} and does not require any other dependencies at runtime; in other words it can be used as is.

[[yarn]]
{eh} binary is suitable for Hadoop 2.x (also known as YARN) environments.
Support for Hadoop 1.x environments are deprecated in 5.5 and will no longer be tested against in 6.0.

=== Minimalistic binaries

In addition to the 'uber' jar, {eh} provides minimalistic jars for each integration, tailored for those who use just _one_ module (in all other situations the `uber` jar is recommended); the jars are smaller in size and use a dedicated pom, covering only the needed dependencies.
These are available under the same `groupId`, using an `artifactId` with the pattern `elasticsearch-hadoop-{integration}`:

.Map/Reduce
["source","xml",subs="attributes"]
----
<dependency>
  <groupId>org.elasticsearch</groupId>
  <artifactId>elasticsearch-hadoop-mr<1></artifactId>
  <version>{ver}</version>
</dependency>
----

<1> 'mr' artifact

.Apache Hive
["source","xml",subs="attributes"]
----
<dependency>
  <groupId>org.elasticsearch</groupId>
  <artifactId>elasticsearch-hadoop-hive<1></artifactId>
  <version>{ver}</version>
</dependency>
----

<1> 'hive' artifact

.Apache Pig
["source","xml",subs="attributes"]
----
<dependency>
  <groupId>org.elasticsearch</groupId>
  <artifactId>elasticsearch-hadoop-pig<1></artifactId>
  <version>{ver}</version>
</dependency>
----

<1> 'pig' artifact

.Apache Spark
["source","xml",subs="attributes"]
----
<dependency>
  <groupId>org.elasticsearch</groupId>
  <artifactId>elasticsearch-spark-20<1>_2.10<2></artifactId>
  <version>{ver}</version>
</dependency>
----

<1> 'spark' artifact. Notice the `-20` part of the suffix which indicates the Spark version compatible with the artifact. Use `20` for Spark 2.0+ and `13` for Spark 1.3-1.6.
<2> Notice the `_2.10` suffix which indicates the Scala version compatible with the artifact. Currently it is the same as the version used by Spark itself.

The Spark connector framework is the most sensitive to version incompatibilities. For your convenience, a version compatibility matrix has been provided below:
[cols="2,2,10",options="header",]
|==========================================================
| Spark Version | Scala Version | ES-Hadoop Artifact ID
| 1.0 - 1.2 | 2.10 | <unsupported>
| 1.0 - 1.2 | 2.11 | <unsupported>
| 1.3 - 1.6 | 2.10 | elasticsearch-spark-13_2.10
| 1.3 - 1.6 | 2.11 | elasticsearch-spark-13_2.11
| 2.0+ | 2.10 | elasticsearch-spark-20_2.10
| 2.0+ | 2.11 | elasticsearch-spark-20_2.11
|==========================================================

.Cascading
["source","xml",subs="attributes"]
----
<dependency>
  <groupId>org.elasticsearch</groupId>
  <artifactId>elasticsearch-hadoop-cascading<1></artifactId>
  <version>{ver}</version>
</dependency>
----

<1> 'cascading' artifact

Note that Cascading itself is not available in Maven central but rather in its own repo http://conjars.org/[conjars.org]. Make sure to add this repository to your build configuration
in order for the Cascading dependencies to be properly resolved:

[source,xml]
----
<repositories>
  <repository>
    <id>conjars.org</id>
    <url>http://conjars.org/repo</url>
  </repository>
</repositories>
----

.Storm
["source","xml",subs="attributes"]
----
<dependency>
  <groupId>org.elasticsearch</groupId>
  <artifactId>elasticsearch-storm<1></artifactId>
  <version>{ver}</version>
</dependency>
----

<1> 'storm' artifact

Releases are available in the central Maven http://repo1.maven.org/maven[repository].

[[download-dev]]
=== Development Builds

Development (or nightly or snapshots) builds are published daily at 'sonatype-oss' repository (see below). Make sure to use snapshot versioning:

["source","xml",subs="attributes"]
----
<dependency>
  <groupId>org.elasticsearch</groupId>
  <artifactId>elasticsearch-hadoop</artifactId>
  <version>{ver-d}</version> <1>
</dependency>
----

<1> notice the 'BUILD-SNAPSHOT' suffix indicating a development build

but also enable the dedicated snapshots repository :

[source,xml]
----
<repositories>
  <repository>
    <id>sonatype-oss</id>
    <url>http://oss.sonatype.org/content/repositories/snapshots</url> <1>
    <snapshots><enabled>true</enabled></snapshots> <2>
  </repository>
</repositories>
----

<1> add snapshot repository
<2> enable 'snapshots' capability on the repository otherwise these will not be found by Maven

[[upgrading]]
=== Upgrading Your Stack

{ehtm} is a client library for {es}, albeit one with extended functionality for supporting operations on Hadoop/Spark. When upgrading Hadoop/Spark versions, it is best to check
to make sure that your new versions are supported by the connector, upgrading your {eh} version as appropriate.

{ehtm} maintains backwards compatibility with the most recent minor version of {es}'s previous major release (5.X supports back to 2.4.X, 6.X supports back to 5.6.X, etc...). When you are upgrading
your version of {es}, it is best to upgrade {eh} to the new version (or higher) first. The new {eh} version should continue to work for your previous
{es} version, allowing you to upgrade as normal.

NOTE: {ehtm} does not support rolling upgrades well. During a rolling upgrade, nodes that {eh} is communicating with will be regularly disappearing and coming back online. Due to the constant connection
failures that {eh} will experience during the time frame of a rolling upgrade there is high probability that your jobs will fail. Thus, it is recommended that you disable
any {eh} based write or read jobs against {es} during your rolling upgrade process.
