[[requirements]]
== Requirements

Before running {eh}, please do check out the requirements below. This is even more so important when deploying {eh} across a cluster where the software on some machines might be slightly out of sync. While {eh} tries its best to fall back and do various validations of its environment, doing a quick sanity check especially during upgrades can save you a lot of headaches.

NOTE: make sure to verify *all* nodes in a cluster when checking the version of a certain artifact.

TIP: {eh} adds no extra requirements to Hadoop (or the various libraries built on top of it, such as Pig) or {es} however as a rule of thumb, do use the latest stable version of the said library (checking the compatibility with Hadoop and the JDK, where applicable).

[[requirements-jdk]]
=== JDK

JDK level 8 (at least u20 or higher). An up-to-date support matrix for Elasticsearch is available https://www.elastic.co/subscriptions/matrix[here]. Do note that the JVM versions are *critical* for a stable environment as an incorrect version can corrupt the data underneath as explained in this http://www.elastic.co/blog/java-1-7u55-safe-use-elasticsearch-lucene/[blog post].

One can check the available JDK version from the command line:

[source,bash]
----
$ java -version
java version "1.8.0_45"
----

[[requirements-es]]
=== {es}

We *highly* recommend using the latest Elasticsearch (currently {elasticsearch_version}). While {eh} maintains backwards compatibility
with previous versions of {es}, we strongly recommend using the latest, stable version of Elasticsearch. You can
find a matrix of supported versions https://www.elastic.co/support/matrix#matrix_compatibility[here].

The {es} version is shown in its folder name:

["source","bash",subs="attributes"]
----
$ ls
elasticsearch-{elasticsearch_version}
----

If {es} is running (locally or remotely), one can find out its version through REST:

["source","js",subs="attributes"]
----
$ curl -XGET http://localhost:9200
{
  "status" : 200,
  "name" : "Dazzler",
  "version" : {
    "number" : "{elasticsearch_version}",
    ...
  },
  "tagline" : "You Know, for Search"
}
----

[[requirements-hadoop]]
=== Hadoop

{eh} is compatible with Hadoop 2 and Hadoop 3 (ideally the latest stable version). It is tested daily against Apache Hadoop, but any distro
compatible with Apache Hadoop should work just fine.

To check the version of Hadoop, one can refer either to its folder or jars (which contain the version in their names) or from the command line:

[source, bash]
----
$ bin/hadoop version
Hadoop 3.3.1
----

[[requirements-hive]]
=== Apache Hive

Apache Hive 0.10 or higher. We recommend using the latest release of Hive (currently {hv-v}).

One can find out the Hive version from its folder name or command-line:

["source","bash",subs="attributes"]
----
$ bin/hive --version
Hive version {hv-v}
----

[[requirements-pig]]
=== Apache Pig

deprecated::[8.0,Support for Apache Pig in {eh} is deprecated.]

Pig 0.10.0 or higher. We recommend using the latest release of Pig (currently {pg-v}).
In a similar fashion, Pig version can be discovered from its folder path or through the command-line:

["source","bash",subs="attributes"]
----
$ bin/pig -i
Apache Pig version {pg-v}
----

[[requirements-spark]]
=== Apache Spark

deprecated::[8.0,Support for Spark 1.x in {eh} is deprecated.]

Spark 1.3.0 or higher. We recommend using the latest release of Spark (currently {sp-v}). As {eh} provides native integration (which is recommended) with {sp}, it does not matter what binary one is using.
The same applies when using the Hadoop layer to integrate the two as {eh} supports the majority of
Hadoop distributions out there.

The Spark version can be typically discovered by looking at its folder name:

["source","bash",subs="attributes"]
----
$ pwd
/libs/spark/spark-{sp-v}-bin-XXXXX
----

or by running its shell:

["source","bash",subs="attributes"]
----
$ bin/spark-shell
...
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version {sp-v}
      /_/
...
----

[[requirements-spark-sql]]
==== Apache Spark SQL

If planning on using Spark SQL make sure to add the appropriate Spark SQL jar as a dependency. While it is part of the Spark distribution,
it is _not_ part of the Spark core jar but rather has its own jar. Thus, when constructing the classpath make sure to
include +spark-sql-<scala-version>.jar+ or the Spark _assembly_ : +spark-assembly-{sp-v}-<distro>.jar+

{eh} supports Spark SQL 1.3 though 1.6, Spark SQL 2.x, and Spark SQL 3.x. {eh} supports Spark SQL 2.x on Scala 2.11 through its main jar.
Since Spark 1.x, 2.x, and 3.x are not compatible with each other, and Scala versions are not compatible, multiple different artifacts are
provided by {eh}. Choose the jar appropriate for your Spark and Scala version. See the Spark chapter for more information.

[[requirements-storm]]
=== Apache Storm

deprecated::[8.0,Support for Apache Storm in {eh} is deprecated.]

Storm 1.0.0 or higher. Do note that Storm 1.0.0 broke backwards compatibility with the previous versions (by changing the package name)
however upgrading is easy and recommended. We recommend using the latest release of Storm (currently {st-v}).
One can discover the Storm version by looking at its folder or by invoking the command:

["source","bash",subs="attributes"]
----
$ bin/storm version
{st-v}
----

