[[install]]
== Installation

{eh} binaries can be obtained either by downloading them from the http://elasticsearch.org[elasticsearch.org] site as a ZIP (containing project jars, sources and documentation) or by using any http://maven.apache.org/[Maven]-compatible tool with the following dependency:

[source,xml]
----
<dependency>
  <groupId>org.elasticsearch</groupId>
  <artifactId>elasticsearch-hadoop</artifactId>
  <version>1.3.0.M3</version>
</dependency>
----

The jar above contains all the features of {eh} and does not require any other dependencies at runtime; in other words it can be used as is.

[[yarn]]
Since 1.3.0.M3, the distribution jar is suitable for both Hadoop 1.x and Hadoop 2.x (also known as YARN) environments.
YARN/Hadoop 2.x/MRv2 binary compatible releases are published using the 'yarn' classifier:

=== Minimalistic binaries

In addition to the 'uber' jar, {eh} provides minimalistic jars for each integration, taylored for those who use just one integration and interested in saving additional space (though the 'uber' jar itself is a mere couple of hundred KB). Thus one can 'select' the needed jar by specifying the library it wants as the
'classifier' (in Maven terminology), as follows:

[source,xml]
----
<dependency>
  <groupId>org.elasticsearch</groupId>
  <artifactId>elasticsearch-hadoop</artifactId>
  <version>1.3.0.M3</version>
  <classifier>mr</classifier><1>
</dependency>
----

<1> classifier selecting the 'mr' artifact

[source,xml]
----
<dependency>
  <groupId>org.elasticsearch</groupId>
  <artifactId>elasticsearch-hadoop</artifactId>
  <version>1.3.0.M3</version>
  <classifier>hive</classifier><1>
</dependency>
----

<1> classifier selecting the 'hive' artifact

[source,xml]
----
<dependency>
  <groupId>org.elasticsearch</groupId>
  <artifactId>elasticsearch-hadoop</artifactId>
  <version>1.3.0.M3</version>
  <classifier>pig</classifier><1>
</dependency>
----

<1> classifier selecting the 'pig' artifact

[source,xml]
----
<dependency>
  <groupId>org.elasticsearch</groupId>
  <artifactId>elasticsearch-hadoop</artifactId>
  <version>1.3.0.M3</version>
  <classifier>cascading</classifier><1>
</dependency>
----

<1> classifier selecting the 'cascading' artifact

Releases are available in the central Maven http://repo1.maven.org/maven[repository].

[[download-dev]]
=== Development Builds

Development (or nightly or snapshots) builds are published daily at 'sonatype-oss' repository (see below). Make sure to use snapshot versioning:

[source,xml]
----
<dependency>
  <groupId>org.elasticsearch</groupId>
  <artifactId>elasticsearch-hadoop</artifactId>
  <version>1.3.0.BUILD-SNAPSHOT</version> <1>
</dependency>
----

<1> notice the 'BUILD-SNAPSHOT' suffix indicating a development build

but also enable the dedicated snapshots repository :

[source,xml]
----
<repositories>
  <repository>
    <id>sonatype-oss</id>
    <url>http://oss.sonatype.org/content/repositories/releases</url> <1>
    <snapshots><enabled>true</enabled></snapshots> <2>
  </repository>
</repositories>
----

<1> add snapshot repository
<2> enable 'snapshots' capability on the repository otherwise these will not be found by Maven