[[install]]
== Installation

{eh} binaries can be obtained either by downloading them from the http://elasticsearch.org[elasticsearch.org] site as a ZIP (containing project jars, sources and documentation) or by using any http://maven.apache.org/[Maven]-compatible tool with the following dependency:

[source,xml]
----
<dependency>
  <groupId>org.elasticsearch</groupId>
  <artifactId>elasticsearch-hadoop</artifactId>
  <version>1.3.0.M2</version>
</dependency>
----

[[yarn]]
YARN/Hadoop 2.x/MRv2 binary compatible releases are published using the 'yarn' classifier:
[source,xml]
----
<dependency>
  <groupId>org.elasticsearch</groupId>
  <artifactId>elasticsearch-hadoop</artifactId>
  <version>1.3.0.M2</version>
  <classifier>yarn</classifier><1>
</dependency>
----

<1> classifier selecting the 'yarn' artifact

CAUTION: Many Hadoop distribution ship both YARN (or MRv2) and Hadoop 1.x (or MRv1) in the same package but running only one package at a time. Use the 'yarn' jars only when running on MRv2 - if you are using MRv1, do use the normal {eh} distribution.

Releases are available in the central Maven http://repo1.maven.org/maven[repository].
Additionally, one can use the following repository which contains both releases and nightly builds (see below):

[source,xml]
----
<repositories>
  <repository>
    <id>sonatype-oss</id>
    <url>http://oss.sonatype.org/content/repositories/releases</url>
  </repository>
</repositories>
----

[[download-dev]]
=== Development Builds

Development (or nightly or snapshots) builds are published daily at the aforementioned 'sonatype-oss' repository. Make sure to
use snapshot versioning:

[source,xml]
----
<dependency>
  <groupId>org.elasticsearch</groupId>
  <artifactId>elasticsearch-hadoop</artifactId>
  <version>1.3.0.BUILD-SNAPSHOT</version> <1>
</dependency>
----

<1> notice the 'SNAPSHOT' suffix indicating a development build

but also enable snapshots in the repository definition:

[source,xml]
----
<repositories>
  <repository>
    <id>sonatype-oss</id>
    <url>http://oss.sonatype.org/content/repositories/releases</url>
    <snapshots><enabled>true</enabled></snapshots> <1>
  </repository>
</repositories>
----

<1> enable snapshots on the repository otherwise these will not be found by Maven
