[[requirements]]
== Requirements

Before running {eh}, please do check out the requirements below. This is even more so important when deploying {eh} across a cluster where the software on some machines might be slightly out of sync. While {eh} tries its best to fall back and do various validations of its environment, doing a quick sanity check especially during upgrades can save you a lot of headaches.

NOTE: make sure to verify *all* nodes in a cluster when checking the version of a certain artifact.

TIP: {eh} adds no extra requirements to Hadoop (or the various libraries built on top of it, such as Cascading or Pig) or {es} however as a rule of thumb, do use the latest stable version of the said library (checking the compatibility with Hadoop and the JDK, where applicable).

[[requirements-jdk]]
=== JDK

JDK level 6.0 (or above) just like Hadoop. We strongly recommend using JDK 6.0 (update 25) or if possible, JDK 7.0 update u55 (required for Elasticsearch 1.2 or higher). See this http://www.elastic.co/blog/java-1-7u55-safe-use-elasticsearch-lucene/[blog post] for more information on why the JVM versions are important (from Lucene point of view) and how some JVM updates (for example anything between JDK 7 update 25 and update 55) can cause index corruption due to some nasty bugs.

One can check the available JDK version from the command line:

[source,bash]
----
$ java -version
java version "1.7.0_55"
----

[[requirements-es]]
=== {es}

version *0.90* or higher, though we highly recommend using the latest Elasticsearch (currently 1.3.x) is needed to run {es}. Using a lower version is not possible as {eh} uses new features added in 0.90 for distributed, parallel interactions with {es}. We strongly recommend using the latest, stable version of Elasticsearch.

The {es} version is shown in its folder name:

[source,bash]
----
$ ls
elasticsearch-1.3.4
----

If {es} is running (locally or remotely), one can find out through REST its version:

[source,js]
----
$ curl -XGET http://localhost:9200
{
  "status" : 200,
  "name" : "Dazzler",
  "version" : {
    "number" : "1.3.4",
    "build_hash" : "a70f3ccb52200f8f2c87e9c370c6597448eb3e45",
    "build_timestamp" : "2014-09-30T09:07:17Z",
    "build_snapshot" : false,
    "lucene_version" : "4.9"
  },
  "tagline" : "You Know, for Search"
}
----

[[requirements-hadoop]]
=== Hadoop

Hadoop 1.x (ideally the latest stable version in the 1.x line, currently 1.2.1) or 2.x (ideally the latest stable version, currently 2.2.0). {eh} is tested daily against Apache Hadoop; any distro compatible with Apache Hadoop should work just fine.

To check the version of Hadoop, one can refer either to its folder or jars (which contain the version in their names) or from the command line:

[source, bash]
----
$ bin/hadoop version
Hadoop 1.2.1
----

As a guide, the table below lists the Hadoop-based distributions against with this version has been tested against at various points in time:

|===
| Distribution		| Release

| Apache Hadoop		| 2.4.x
| Apache Hadoop		| 2.2.x
| Apache Hadoop		| 1.2.x
| Apache Hadoop		| 1.1.x

| Amazon EMR		| 3.1.x
| Amazon EMR		| 3.0.x
| Amazon EMR		| 2.4.x

| Cloudera CDH		| 5.1.x
| Cloudera CDH		| 5.0.x
| Cloudera CDH		| 4.5.x
| Cloudera CDH		| 4.4.x
| Cloudera CDH		| 4.2.2

| Hortonworks HDP   | 2.1.x
| Hortonworks HDP   | 2.0.x
| Hortonworks HDP   | 1.3.x

| Greenplum GPHD   	| 1.2
| Intel	Hadoop		| 2.5.1

| Pivotal HD   		| 2.1.x
| Pivotal HD   		| 2.0.x
| Pivotal HD   		| 1.1.x

| MapR				| 4.0.x
| MapR				| 3.1.x
| MapR				| 3.0.x
| MapR				| 2.1.x
|===

IMPORTANT: Use the table above for guidance only; if your distro (or its version) is not there, it does not mean {eh} is not compatible with it; rather go ahead and try it out and let us know how it went.

[[requirements-yarn]]
=== Apache YARN / Hadoop 2.x

{eh} binary can run transparently on both Hadoop 1.x and Yarn / Hadoop 2.x without any changes or modifications.

[[requirements-cascading]]
=== Cascading

Cascading version 2.1.x (2.1.6) or higher. We recommend using the latest release of Cascading (currently 2.5.6).

Since Cascading is a library, the best way to find out the target version is to look at its file name:

[source, bash]
----
$ ls
cascading-2.5.6.jar
----

[[requirements-hive]]
=== Apache Hive

Apache Hive 0.9 or higher. We recommend using the latest release of Hive (currently 0.12.0 or 0.13.1).

One can find out the Hive version from its folder name or command-line:

[source, bash]
----
$ bin/hive --version
Hive version 0.13.1
----

[[requirements-pig]]
=== Apache Pig

Pig 0.10.0 or higher. We recommend using the latest release of Pig (currently 0.13).

In a similar fashion, Pig version can be discovered from its folder path or through the command-line:

[source, bash]
----
$ bin/pig -i
Apache Pig version 0.13.0
----
