language: java
jdk:
 - oraclejdk8
 - oraclejdk11


dist: trusty

before_install:
 - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
 - "chmod +x gradlew"
 - export JAVA_OPTS="-Xmx2048m -XX:MaxPermSize=386m"

install: ./gradlew assemble -Pskip.signing
