language: java
jdk:
  - openjdk8

dist: xenial

before_install:
 - "chmod +x gradlew"
 - export JAVA_OPTS="-Xmx2048m -XX:MaxPermSize=386m"

install:
 - export JAVA8_HOME=~/oraclejdk8
 - export JAVA12_HOME=~/openjdk12
 - ~/bin/install-jdk.sh --target $JAVA12_HOME --workspace "/home/travis/.cache/install-jdk" --feature "12" --license "GPL" --cacerts
 - jdk_switcher use openjdk12
 - ./gradlew assemble -Pskip.signing
