language: java
jdk:
  - openjdk12
  - oraclejdk8

dist: xenial

before_install:
 - "chmod +x gradlew"
 - export JAVA_OPTS="-Xmx2048m -XX:MaxPermSize=386m"

install:
 - export JAVA8_HOME=~/oraclejdk8
 - jdk_switcher use openjdk12
 - ./gradlew assemble -Pskip.signing
