language: java
jdk:
 - oraclejdk11

script:
  - export JAVA_HOME=$HOME/oraclejdk8
  - $TRAVIS_BUILD_DIR/install-jdk.sh --install oraclejdk8 --target $JAVA_HOME

dist: trusty

before_install:
 - "chmod +x gradlew"
 - export JAVA_OPTS="-Xmx2048m -XX:MaxPermSize=386m"

install: ./gradlew assemble distribution -Pskip.signing
