---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-elasticsearch-hadoop
  description: Runs full suite of elasticsearch-hadoop tests
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/elasticsearch-hadoop-tests
spec:
  type: buildkite-pipeline
  system: buildkite
  owner: group:elasticsearch-team
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      description: 'Runs full suite of elasticsearch-hadoop tests'
      name: elasticsearch-hadoop / tests
    spec:
      repository: elastic/elasticsearch-hadoop
      pipeline_file: .buildkite/pipeline.py
      default_branch: main
      branch_configuration: 'main 8.* 7.17'
      teams:
        elasticsearch-team: {}
        everyone:
          access_level: BUILD_AND_READ
      provider_settings:
        trigger_mode: none
        build_pull_requests: true
        build_pull_request_forks: false
        publish_commit_status: true
        build_branches: true
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-elasticsearch-hadoop-on-merge
  description: Runs full suite of elasticsearch-hadoop tests and publishes DRA snapshot
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/elasticsearch-hadoop-on-merge
spec:
  type: buildkite-pipeline
  system: buildkite
  owner: group:elasticsearch-team
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      description: 'Runs full suite of elasticsearch-hadoop tests and publishes DRA snapshot'
      name: elasticsearch-hadoop / on-merge
    spec:
      repository: elastic/elasticsearch-hadoop
      pipeline_file: .buildkite/pipeline.py
      env:
        ENABLE_DRA_WORKFLOW: 'true'
      default_branch: main
      branch_configuration: 'main 8.* 7.17'
      teams:
        elasticsearch-team: {}
        everyone:
          access_level: BUILD_AND_READ
      provider_settings:
        trigger_mode: code
        build_pull_requests: false
        build_pull_request_forks: false
        publish_commit_status: true
        build_branches: true
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-elasticsearch-hadoop-dra-workflow
  description: Publishes DRA snapshot or staging candidate
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/elasticsearch-hadoop-dra-workflow
spec:
  type: buildkite-pipeline
  system: buildkite
  owner: group:elasticsearch-team
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      description: 'Publishes DRA snapshot or staging candidate'
      name: elasticsearch-hadoop / dra-workflow
    spec:
      repository: elastic/elasticsearch-hadoop
      pipeline_file: .buildkite/dra-workflow.yml
      env:
        ENABLE_DRA_WORKFLOW: 'true'
      default_branch: main
      branch_configuration: 'main 8.* 7.17'
      cancel_intermediate_builds: false
      skip_intermediate_builds: false
      teams:
        elasticsearch-team: {}
        everyone:
          access_level: BUILD_AND_READ
      provider_settings:
        trigger_mode: none
        build_pull_requests: false
        build_pull_request_forks: false
        publish_commit_status: false
        build_branches: false
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-elasticsearch-hadoop-dra-workflow-trigger
  description: Publishes DRA snapshot or staging candidate
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/elasticsearch-hadoop-dra-workflow-trigger
spec:
  type: buildkite-pipeline
  system: buildkite
  owner: group:elasticsearch-team
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      description: 'Publishes DRA snapshot or staging candidate'
      name: elasticsearch-hadoop / dra-workflow-trigger
    spec:
      repository: elastic/elasticsearch-hadoop
      pipeline_file: .buildkite/dra-workflow.trigger.sh
      default_branch: main
      branch_configuration: main
      teams:
        elasticsearch-team: {}
        everyone:
          access_level: BUILD_AND_READ
      provider_settings:
        trigger_mode: none
        build_pull_requests: false
        build_pull_request_forks: false
        publish_commit_status: false
        build_branches: false
      schedules:
        Periodically on main:
          branch: main
          cronline: '0 0,12 * * * America/New_York'
          message: 'Triggers DRA snapshot workflows 2x per day'
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-elasticsearch-hadoop-tests-trigger
  description: Triggers test pipelines once per day
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/elasticsearch-hadoop-tests-trigger
spec:
  type: buildkite-pipeline
  system: buildkite
  owner: group:elasticsearch-team
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      description: 'Triggers test pipelines once per day'
      name: elasticsearch-hadoop / tests-trigger
    spec:
      repository: elastic/elasticsearch-hadoop
      pipeline_file: .buildkite/tests.trigger.sh
      default_branch: main
      branch_configuration: main
      teams:
        elasticsearch-team: {}
        everyone:
          access_level: BUILD_AND_READ
      provider_settings:
        trigger_mode: none
        build_pull_requests: false
        build_pull_request_forks: false
        publish_commit_status: false
        build_branches: false
      schedules:
        Daily on main:
          branch: main
          cronline: '0 4 * * * America/New_York'
          message: 'Triggers test pipelines once per day'
