[[arch]]
== Architecture

At the core, {eh} integrates two _distributed_ systems: *Hadoop*, a distributed computing platform and *{es}*, a real-time search and analytics engine. From a high-level view both provide a computational component: Hadoop through {mr} or recent libraries like {sp} on one hand, and {es} through its search and aggregation on the other.

{eh} goal is to 'connect' these two entities so that they can transparently benefit from each other.

[[arch-shards]]
[float]
=== {mr} and Shards

A critical component for scalability is parallelism or splitting a task into multiple, smaller ones that execute at the same time, on different nodes in the cluster. The concept is present in both Hadoop through its `splits` (the number of parts in which a source or input can be divided) and {es} through {glossary}/terms.html#glossary-shard[`shards`] (the number of parts in which a index is divided into).

In short, roughly speaking more input splits means more tasks that can read at the same time, different parts of the source. More shards means more 'buckets' from which to read an index content (at the same time).

As such, {eh} uses splits and shards as the main drivers behind the number of tasks executed within the Hadoop and {es} clusters as they have a direct impact on parallelism.

TIP: Hadoop `splits` as well as {es} `shards` play an important role regarding a system behavior - we recommend familiarizing with the two concepts to get a better understanding of your system runtime semantics.

[[arch-spark]]
[float]
=== {sp} and Shards

While {sp} is not built on top of {mr} it shares similar concepts: it features the concept of `partition` which is the rough equivalent of {es} `shard` or the {mr} `split`. Thus, the analogy above applies here as well - more shards and/or more partitions increase the number of parallelism and thus allows both systems to scale better.

NOTE: Due to the similarity in concepts, through-out the docs one can think interchangebly of Hadoop `InputSplit` s and Spark `Partition` s.

[[arch-reading]]
[float]
=== Reading from {es}

Shards play a critical role when reading information from {es}. Since it acts as a source, {eh} will create one Hadoop `InputSplit` per {es} shard, or in case of {sp} one `Partition`, that is given a query that works against index `I`. {eh} will dynamically discover the number of shards backing `I` and then for each shard will create, in case of Hadoop an input split (which will determine the maximum number of Hadoop tasks to be executed) or in case of Spark a partition which will determine the `RDD` maximum parallelism.

With the default settings, {es} uses *5* {glossary}/terms.html#glossary-primary-shard[`primary`] shards per index which will result in the same number of tasks on the Hadoop side for each query.

NOTE: {eh} does not query the same shards - it iterates through all of them (primaries and replicas) using a round-robin approach. To avoid data duplication, only one shard is used from each shard group (primary and replicas).

A common concern (read optimization) for improving performance is to increase the number of shards and thus increase the number of tasks on the Hadoop side. Unless such gains are demonstrated through benchmarks, we recommend against such a measure since in most cases, an {es} shard can *easily* handle data streaming to a Hadoop or Spark task.

[[arch-writing]]
[float]
=== Writing to {es}

Writing to {es} is driven by the number of Hadoop input splits (or tasks) or Spark partitions available. {eh} detects the number of (primary) shards where the write will occur and distributes the writes between these. The more splits/partitions available, the more mappers/reducers can write data in parallel to {es}.

[[arch-colocation]]
[float]
=== Data co-location

Whenever possible, {eh} shares the {es} cluster information with Hadoop and Spark to facilitate data co-location. In practice, this means whenever data is read from {es}, the source nodes' IPs are passed on to Hadoop and Spark to optimize task execution. If co-location is desired/possible, hosting the {es} and Hadoop and Spark clusters within the same rack will provide significant network savings.
