[[cascading]]
== Cascading support

[quote, Cascading website]
____
http://www.cascading.org/[Cascading] is a data processing API and processing query planner used for defining, sharing, and executing data-processing workflows on a single computing node or distributed computing cluster. 
____

Cascading abstracting the {mr} API and focusing on http://docs.cascading.org/cascading/2.1/userguide/htmlch03.html[data processing] 
in terms of 'tuples' http://docs.cascading.org/cascading/2.1/userguide/htmlch03s08.html['flowing'] through http://docs.cascading.org/cascading/2.1/userguide/htmlch03s02.html[pipes] between http://docs.cascading.org/cascading/2.1/userguide/htmlch03s05.html['taps'], 
from input (called `SourceTap`) to output (named `SinkTap`). As the data flows, various operations are applied to the tuple; the whole system being transformed to {mr} operations at runtime.
With {eh}, {es} can be plugged into Cascading flows as a `SourceTap` or `SinkTap` through `EsTap`.

****
.Local or Hadoop mode?
Cascading supports two 'execution' modes or http://docs.cascading.org/cascading/2.1/userguide/htmlch03s04.html[platforms]:

Local:: for unit testing and quick POCs. Everything runs only on the local machine and file-system.
Hadoop:: production mode - connects to a proper Hadoop cluster (as oppose to the 'local' mode which is running just on the local machine).

{eh} supports *both* platforms automatically. One does not have to choose between different classes, `EsTap` can be used as both `sink` or `source`, in both modes transparently.
****

[float]
=== Installation

Just like other libraries, {eh} needs to be available in the jar classpath (either by being manually deployed in the cluster or shipped along with the Hadoop job).

[float]
=== Configuration

[float]
==== Global configuration
Cascading is configured through a `Map<Object, Object>`, typically a `Properties` object which indicates the various Cascading settings and also the application jar:

[source,java]
----
Properties props = new Properties();
AppProps.setApplicationJarClass(props, Main.class);
FlowConnector flow = new HadoopFlowConnector(props);
----

{eh} options can be specified in the same way, these being picked up automatically by _all_ `EsTap`s down the flow:

[source,java]
----
Properties props = new Properties();
props.setProperty("es.index.auto.create", "false"); <1>
...
FlowConnector flow = new HadoopFlowConnector(props);
----

<1> set {eh} option

This approach can be used for local and remote/Hadoop flows - simply use the appropriate `FlowConnector`.

[float]
==== Per-`Tap` configuration
If a `flow` contains multiple `{es}` taps, the global approach does not work since the settings will clash with each other.  For these scenario, `{eh}` allows using per-`Tap` configuration:

[source,java]
----
Tap books = new EsTap("es-server", 9200, "my-col/books", "?q=potter");
Tap movies = new EsTap("es-server", 9200, "my-col/movies", "?q=terminator");
----

Note that the `Tap` configuration is merged with the global one so one can mix and match accordingly - for example specify the defaults in the global configuration and only declare the specifics on the `Tap` instance. Additionally, for maximum flexibility `EsTap` allows multiple arguments to be passed in, including a `Properties` object for the full range of options.


[[cascading-writing]]
[float]
=== Writing data to {es}

Simply hook, `EsTap` into the Cascading flow:

[source,java]
----
Tap in = Lfs(new TextDelimited(new Fields("id", "name", "url", "picture")), 
             "/resources/artists.dat");
Tap out = new EsTap("radio/artists" <1>, new Fields("name", "url", "picture") <2>);
new HadoopFlowConnector().connect(in, out, new Pipe("write-to-Es")).complete();
----

<1> {eh} resource (index and type)
<2> Cascading tuple declaration

[float]
==== Writing JSON directly to {es}

When the job output data is already in JSON, {eh} allows direct indexing _without_ applying any transformation; the data is taken as is and sent directly to {es}. In such cases, one needs to indicate the json input by setting
the `es.input.json` parameter. As such, in this case {eh} expects to receive a tuple with a single field (representing the JSON document); the library will recognize `Text` or `BytesWritable` types otherwise it just
calls `toString` to get a hold of the JSON content.

IMPORTANT: Make sure the data is properly encoded, in `UTF-8`. The job output is considered the final form of the document sent to {es}.

[source,java]
----
Properties props = new Properties();
...
props.setProperty("es.input.json", "true");                                   <1>
Tap in = new Lfs(new TextLine(new Fields("line")),"/resources/artists.json"); <2>
Tap out = new EsTap("json-cascading-local/artists");
FlowConnector flow = new HadoopFlowConnector(props);
flow.connect(in, out, new Pipe("import-json")).complete();
----

<1> Indicate the input is of type JSON.
<2> Load the (JSON) data as a single field (`line`)


[float]
==== Writing to dynamic/multi-resources

One can index the data to a different resource, depending on the tuple being read by using patterns. Reusing the aforementioned <<cfg-multi-writes,media example>>, one could configure it as follows:

[source,java]
----
Tap out = new EsTap("es.resource.write", "my-collection/{media.type}");
----

For each tuple about to be written, {eh} will extract the `media.type` entry and use its value to determine the target resource. The functionality is available when dealing with raw JSON as well - the value will be extracted from the document itself.

[float]
=== Reading data from {es}

Just the same, add `EsTap` on the other end of a pipe, to read (instead of writing) to it.

[source,java]
----
Tap in = new EsTap("radio/artists/"<1>,"?q=me*"<2>);
Tap out = new StdOut(new TextLine());
new LocalFlowConnector().connect(in, out, new Pipe("read-from-Es")).complete();
----

<1> {eh} resource (index and type)
<2> {eh} query


[float]
=== Type conversion

Depending on the http://docs.cascading.org/cascading/2.1/userguide/htmlch03s04.html[platform] used, Cascading can use internally either `Writable` or JDK types for its tuples. {es} handles both transparently 
(see the {mr} <<type-conversion-writable,conversion>> section) though we recommend using the same types (if possible) in both cases to avoid the overhead of maintaining two different versions.

IMPORTANT: If automatic index creation is used, please review <<auto-mapping-type-loss,this>> section for more information.
