= Reference

[partintro]
--
This part of the documentation explains the core functionality of {eh} starting with the configuration options and architecture and gradually explaining the various major features. We recommend going through the entire documentation even superficially when trying out {eh} for the first time, however those in a rush, can jump directly to the desired sections:

<<architecture>>:: overview of the {eh} architecture and how it maps on top of {mr}

<<configuration>>:: explore the various configuration switches in {eh}

<<mapreduce>>:: describes how to use {eh} in vanilla {mr} environments - typically useful for those interested in data loading and saving to/from {es} without little, if any, ETL (extract-transform-load).

<<cascading>>:: describes how to use Cascading and {eh}.

<<hive>>:: Hive users should refer to this section.

<<pig>>:: how-to on using {es} in Pig scripts through {eh}.

<<mapping>>:: deep-dive into the strategies employed by {eh} for doing type conversion and mapping to and from {es}.
--
