[[reference]]
= Reference

[partintro]
--
This part of the documentation explains the core functionality of {eh} starting with the configuration options and architecture and gradually explaining the various major features. At a higher level the reference is broken down into architecture and configuration section which are general, {mr} and the libraries built on top of it, upcoming computation libraries (like {sp}) and finally mapping, metrics and troubleshooting.
We recommend going through the entire documentation even superficially when trying out {eh} for the first time, however those in a rush, can jump directly to the desired sections:

<<arch>>:: overview of the {eh} architecture and how it maps on top of Hadoop

<<configuration>>:: explore the various configuration switches in {eh}

<<mapreduce>>:: describes how to use {eh} in vanilla {mr} environments - typically useful for those interested in data loading and saving to/from {es} without little, if any, ETL (extract-transform-load).

<<cascading>>:: describes how to use Cascading and {eh}.

<<hive>>:: Hive users should refer to this section.

<<pig>>:: how-to on using {es} in Pig scripts through {eh}.

<<spark>>:: describes how to use Apache Spark with {es} through {eh}.

<<mapping>>:: deep-dive into the strategies employed by {eh} for doing type conversion and mapping to and from {es}.

<<metrics>>:: Elasticsearch Hadoop metrics

<<troubleshooting>>:: tips on troubleshooting and getting help
--
