[[performance]]
== Performance considerations

The runtime performance of using Elasticsearch for Apache Hadoop depends on a variaty of factors; the same setup
can yield great results on a dataset but 'struggle' on a different one.
This section tries to summarize a list of commons things to look for and ways to address them.

=== Measure do not assume (to be read guess)

First and foremost, when encountering a performance issue, do some benchmarking and try to isolate the problem. Do not simply assume a certain component is wrong; make sure/prove it actually is. Otherwise, more often than not, one might find herself fixing the wrong problem.

=== Find a baseline

Indexing performance depend _heavily_ on the type of data being targeted and its mapping. Same goes for searching but add the query definition to the mix. As mentioned before, experiment and measure the various parts of your dataset before importing/searching big amounts of data.

=== Hardware is king

Faster, better hardware means better performance.

=== Monitor I/O



=== Avoid overloading


- increase network buffer size
- number of mappers/reducers
- use mapper/streaming mainly
- use a reducer to limit the number of writes
- pay attention to network I/O
- pay attention to memory usage
- disable replicas (when loading a lot of data)
- consider using snapshot/restore
