steps:
  - label: DRA Workflow
    command: .buildkite/dra.sh
    timeout_in_minutes: 60
    env:
      USE_DRA_CREDENTIALS: true
    agents:
      provider: gcp
      image: family/elasticsearch-ubuntu-2004
      machineType: n2-standard-8
      diskType: pd-ssd
      diskSizeGb: 100
