= Elasticsearch for Apache Hadoop

:icons:
:ehtm: 	Elasticsearch for Apache Hadoop
:eh: 	elasticsearch-hadoop
:es: 	Elasticsearch
:mr: 	Map/Reduce
:sp:	Apache Spark
:st:	Apache Storm
:ey:	Elasticsearch on YARN
:ref:  	http://www.elastic.co/guide/en/elasticsearch/reference/5.0
:description: Reference documentation of {eh}
:ver:	5.6.3
:ver-d: 5.6.4.BUILD-SNAPSHOT
:es-v:	5.6.3
:sp-v:	1.6.2
:st-v:	1.0.1
:pg-v:	0.15.0
:hv-v:	1.2.1
:cs-v:	2.6.3



[[float]]
[preface]
== Preface

{ehtm} is an `umbrella' project consisting of three similar, yet independent sub-projects with their own, dedicated, section in the documentation:

{eh} proper:: interact with {es} from within a Hadoop environment. If you are using {mr}, Hive, Pig, {sp}, {st}, or Cascading, this project is for you. For feature requests or bugs, please open an issue in the https://github.com/elastic/elasticsearch-hadoop/issues[Elasticsearch-Hadoop repository].

repository-hdfs:: use HDFS as a back-end repository for doing snapshot/restore from/to {es}. For more information, refer to its https://www.elastic.co/guide/en/elasticsearch/plugins/master/repository-hdfs.html[home page]. For feature requests or bugs, please open an issue in the https://github.com/elastic/elasticsearch/issues[Elasticsearch repository] with the ":Plugin Repository HDFS" tag.

{ey}:: run {es} on top of YARN - see <<es-yarn>>. This project is in beta.


Thus, while all projects fall under the Hadoop umbrella, each is covering a certain aspect of it so please be sure to read the appropriate documentation. For general questions around any of these projects, the https://discuss.elastic.co/c/elasticsearch-and-hadoop[Elastic Discuss forum] is a great place to interact with other users in the community.

include::core/index.adoc[]

include::yarn/index.adoc[]

include::appendix/index.adoc[]

