= Elasticsearch for Apache Hadoop

:icons:
:ehtm: 	Elasticsearch for Apache Hadoop
:eh: 	elasticsearch-hadoop
:mr: 	Map/Reduce
:sp:	Apache Spark
:st:	Apache Storm
:krb:   Kerberos
:ey:	Elasticsearch on YARN
:description: Reference documentation of {eh}
:ver-d: {version}-SNAPSHOT
:sp-v:	3.2.0
:st-v:	1.0.1
:pg-v:	0.15.0
:hv-v:	2.3.8
:cs-v:	2.6.3
:hadoop-docs-v: 3.3.1

include::{asciidoc-dir}/../../shared/versions/stack/{source_branch}.asciidoc[]
include::{asciidoc-dir}/../../shared/attributes.asciidoc[]

[[float]]
[preface]
== Preface

{ehtm} is an `umbrella' project consisting of two similar, yet independent sub-projects with their own, dedicated, section in the documentation:

{eh} proper::
Interact with {es} from within a Hadoop environment. If you are using {mr}, Hive, Pig, {sp}, or {st}, this
project is for you. For feature requests or bugs, please open an issue in the
https://github.com/elastic/elasticsearch-hadoop/issues[Elasticsearch-Hadoop repository].

repository-hdfs::
Use HDFS as a back-end repository for doing snapshot/restore from/to {es}. For more information, refer to its
{plugins}/repository-hdfs.html[home page]. For feature requests or
bugs, please open an issue in the https://github.com/elastic/elasticsearch/issues[Elasticsearch repository] with the
":Plugin Repository HDFS" tag.

Thus, while all projects fall under the Hadoop umbrella, each is covering a certain aspect of it so please be sure to read the appropriate documentation. For general questions around any of these projects, the https://discuss.elastic.co/c/elasticsearch-and-hadoop[Elastic Discuss forum] is a great place to interact with other users in the community.

include::core/index.adoc[]

include::appendix/index.adoc[]

