[[eshadoop-5.0.0]]
== Elasticsearch for Apache Hadoop version 5.0.0
October 26, 2016

[[breaking-5.0.0]]
=== Breaking Changes
* Update to compat with Storm 1.x.x
http://github.com/elastic/elasticsearch-hadoop/issues/769[#769]
* Why does EsBolt still use the old JAR
http://github.com/elastic/elasticsearch-hadoop/issues/754[#754]
* Drop HDFS repository
http://github.com/elastic/elasticsearch-hadoop/issues/741[#741]
* Drop support for Spark 1.0-1.2
http://github.com/elastic/elasticsearch-hadoop/issues/740[#740]
* Remove legacy Hive version
http://github.com/elastic/elasticsearch-hadoop/issues/739[#739]

[[new-5.0.0]]
=== New Features
Mapping::
* Add support for 16-bit/half floats in ES 5.x
http://github.com/elastic/elasticsearch-hadoop/issues/800[#800]
* New ES type scaled_float
http://github.com/elastic/elasticsearch-hadoop/issues/822[#822]
MR::
* Integrating with ES ingest node pipeline
http://github.com/elastic/elasticsearch-hadoop/issues/806[#806]
New Slice API::
* Add the ability to create IndexPartition based on the desired
number of documents per split
http://github.com/elastic/elasticsearch-hadoop/issues/812[#812]
(issue: http://github.com/elastic/elasticsearch-hadoop/issues/778[#778])
Spark::
* Support for Spark 2.0 / Datasets
http://github.com/elastic/elasticsearch-hadoop/issues/647[#647]
* Provided dedicated support for Spark 1.3-1.6 DStreams
http://github.com/elastic/elasticsearch-hadoop/issues/[#802]

[[enhancements-5.0.0]]
=== Enhancements
Build::
* 2.3.1 release notes list many bugs as fixed without commits
http://github.com/elastic/elasticsearch-hadoop/issues/770[#770]
REST::
* Expire Unused Pooled Transports in Spark Streaming
http://github.com/elastic/elasticsearch-hadoop/issues/849[#849]
* Validate field exclusion settings when EsSpark.saveJsonToEs()
is executed
http://github.com/elastic/elasticsearch-hadoop/issues/782[#782]
* Review the error messages in ES 5.x and properly parse them
http://github.com/elastic/elasticsearch-hadoop/issues/779[#779]
* Align extended Boolean parsing with Elasticsearch
http://github.com/elastic/elasticsearch-hadoop/issues/798[#798]
* Fields replacement in es.update.script.params fails for objects
http://github.com/elastic/elasticsearch-hadoop/issues/760[#760]
* Replace/Ignore DOT character in field names before inserting
into Elastic Search
http://github.com/elastic/elasticsearch-hadoop/issues/758[#758]
Spark::
* Improve ElasticsearchRelation extensibility
http://github.com/elastic/elasticsearch-hadoop/issues/829[#829]
* Explicitly specify buildScan return type
http://github.com/elastic/elasticsearch-hadoop/issues/826[#826]
* Upgrade to Spark 1.6.2
http://github.com/elastic/elasticsearch-hadoop/issues/797[#797]
* Fix example for spark.
http://github.com/elastic/elasticsearch-hadoop/issues/768[#768]
(issue: http://github.com/elastic/elasticsearch-hadoop/issues/767[#767])

[[bugs-5.0.0]]
=== Bug Fixes
Build::
* Repository HDFS still referred in the build system
http://github.com/elastic/elasticsearch-hadoop/issues/775[#775]
* Spark 1.2 artifacts are still referenced
http://github.com/elastic/elasticsearch-hadoop/issues/774[#774]
Hive::
* Date type not properly inserted into ES
http://github.com/elastic/elasticsearch-hadoop/issues/757[#757]
MR::
* Reading boolean 0/1 values from ES into Spark does not work
(although false/true is ok)
http://github.com/elastic/elasticsearch-hadoop/issues/795[#795]
* Elasticsearch Mapreduce write "es.mapping.exclude" not working
http://github.com/elastic/elasticsearch-hadoop/issues/752[#752]
MR and Spark::
* Restore data locality preference for hadoop and spark
http://github.com/elastic/elasticsearch-hadoop/issues/819[#819]
(issue: http://github.com/elastic/elasticsearch-hadoop/issues/814[#814])
NetworkClient::
* Node [127.0.0.1:9200] failed (Read timed out); no other nodes
left - aborting...
http://github.com/elastic/elasticsearch-hadoop/issues/753[#753]
*  Invalid target URI POST@null/pharmadata/test/_search
http://github.com/elastic/elasticsearch-hadoop/issues/748[#748]
Pig::
* Pig maps can have values of different types
http://github.com/elastic/elasticsearch-hadoop/issues/777[#777]
Rest::
* Update/Upsert bulk actions with scripts are broken for ES 1.x as of 5.0.0-alpha5
http://github.com/elastic/elasticsearch-hadoop/issues/817[#817]
* Shard size estimations for Slice API do not target shards
http://github.com/elastic/elasticsearch-hadoop/issues/843[#843]
* Elasticsearch-spark connector failing to save data with an Illegal
Argument Exception : "No class name given"
http://github.com/elastic/elasticsearch-hadoop/issues/837[#837]
* Spark Datasource: Non empty BINARY fields are always considered empty
http://github.com/elastic/elasticsearch-hadoop/issues/835[#835]
* Fix memory leak caused by re-wrapping DelegatedProtocol
http://github.com/elastic/elasticsearch-hadoop/issues/823[#823]
* Fixed parsing of ES mapping with OBJECT field named 'properties'
http://github.com/elastic/elasticsearch-hadoop/issues/810[#810]
(issue: http://github.com/elastic/elasticsearch-hadoop/issues/809[#809])
* Not all errors in ES are reported when writing
http://github.com/elastic/elasticsearch-hadoop/issues/720[#720]
* es.index.auto.create setting doesn't work as expected
http://github.com/elastic/elasticsearch-hadoop/issues/793[#793]
* Parsing error messages can cause a NPE
http://github.com/elastic/elasticsearch-hadoop/issues/776[#776]
* shard preference concatenation with | gives query error
https://github.com/elastic/elasticsearch-hadoop/issues/874[#874]
Spark::
* Dropping a whole column of a DataFrame while indexing the DF into ES
http://github.com/elastic/elasticsearch-hadoop/issues/841[#841]
* Fix: Non empty BINARY fields are considered empty
http://github.com/elastic/elasticsearch-hadoop/issues/834[#834]
* saveToEs saves fields with NULL values
http://github.com/elastic/elasticsearch-hadoop/issues/792[#792]
* Failed to write data back to ES by using Spark DataFrame save() API !!
http://github.com/elastic/elasticsearch-hadoop/issues/749[#749]
* Pushdown option not working as expected with Spark data frames
http://github.com/elastic/elasticsearch-hadoop/issues/734[#734]
URLDecoder::
* Illegal hex characters in escape (%) pattern - For input string: " S"
http://github.com/elastic/elasticsearch-hadoop/issues/747[#747]
Yarn::
* Authenticate with a local keytab in the YARN Application Master
http://github.com/elastic/elasticsearch-hadoop/issues/807[#807]

[[docs-5.0.0]]
=== Documentation
* es.read.field.as.array.include NOT es.field.read.as.array.include
http://github.com/elastic/elasticsearch-hadoop/issues/860[#860]
* Corrected property name
http://github.com/elastic/elasticsearch-hadoop/issues/805[#805]
* Repository HDFS doc improvements
http://github.com/elastic/elasticsearch-hadoop/issues/781[#781]
* Snapshot Creation Exception
http://github.com/elastic/elasticsearch-hadoop/issues/813[#813]
* Corrected link to 'ADD' command
http://github.com/elastic/elasticsearch-hadoop/issues/788[#788]
* Update spark.adoc
http://github.com/elastic/elasticsearch-hadoop/issues/785[#785]
* Update cloud.adoc
http://github.com/elastic/elasticsearch-hadoop/issues/773[#773]
* Update configuration.adoc
http://github.com/elastic/elasticsearch-hadoop/issues/772[#772]
* Tests fail in build
http://github.com/elastic/elasticsearch-hadoop/issues/755[#755]
* Documentation Issue : Wrong package name
https://github.com/elastic/elasticsearch-hadoop/issues/838[#838]
* ES_CLASSPATH removed from ES 2.x
https://github.com/elastic/elasticsearch-hadoop/issues/861[#861]

[[nonissue-5.0.0]]
=== Non-issue
Hive::
* Error Loading Data
http://github.com/elastic/elasticsearch-hadoop/issues/839[#839]
* EsHadoopIllegalArgumentException: Cannot detect ES version
http://github.com/elastic/elasticsearch-hadoop/issues/794[#794]
* ES-Hive throwing exception while reading for bulk no. of columns
http://github.com/elastic/elasticsearch-hadoop/issues/790[#790]
* Create a external table with 'location' command success while
elasticsearch-hadoop do not support 'location' function
http://github.com/elastic/elasticsearch-hadoop/issues/786[#786]
Pig::
* Store Map as object with Pig in Elasticsearch
http://github.com/elastic/elasticsearch-hadoop/issues/848[#848]
* Get fields with documents in Elasticsearch
http://github.com/elastic/elasticsearch-hadoop/issues/825[#825]
* Failure while using EsStorage twice on a single Pig script to store a Parent Child relation
http://github.com/elastic/elasticsearch-hadoop/issues/756[#756]
* Store Tuple as object with Pig in Elasticsearch
http://github.com/elastic/elasticsearch-hadoop/issues/746[#746]
REST::
* Some way to query "total" field from result set?
http://github.com/elastic/elasticsearch-hadoop/issues/830[#830]
* PROBLEM: Failed to write data back to ES by using Spark DataFrame save() API !!
http://github.com/elastic/elasticsearch-hadoop/issues/836[#836]
* Elasticsearch : Cannot detect ES version
http://github.com/elastic/elasticsearch-hadoop/issues/791[#791]
Spark::
* Class Not Found Exception
http://github.com/elastic/elasticsearch-hadoop/issues/863[#863]
* java.lang.NoClassDefFoundError: scala/collection/GenTraversableOnce$class
http://github.com/elastic/elasticsearch-hadoop/issues/862[#862]
* Array types not supported in automatic mapping
http://github.com/elastic/elasticsearch-hadoop/issues/847[#847]
* Connection error with Elasticsearch 2.4.0
http://github.com/elastic/elasticsearch-hadoop/issues/846[#846]
* Handling decimal type in dataset
http://github.com/elastic/elasticsearch-hadoop/issues/842[#842]
* Fix import of JavaEsSparkSQL
http://github.com/elastic/elasticsearch-hadoop/issues/840[#840]
* Got exception when I tried to invoke _mtermvector
http://github.com/elastic/elasticsearch-hadoop/issues/796[#796]
* ES-Hadoop on Spark 2.0
http://github.com/elastic/elasticsearch-hadoop/issues/759[#759]
* elasticsearch-hadoop exception about mapping
http://github.com/elastic/elasticsearch-hadoop/issues/766[#766]
* Parameter ES_MAPPING_TIMESTAMP is not working using saveToEs
http://github.com/elastic/elasticsearch-hadoop/issues/765[#765]